# Generated by Django 4.1.5 on 2023-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20170819_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallrating',
            name='category',
            field=models.CharField(blank=True, choices=[], max_length=250),
        ),
        migrations.AlterField(
            model_name='rating',
            name='category',
            field=models.CharField(blank=True, choices=[], max_length=250),
        ),
    ]
